#!/usr/bin/env python3
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import argparse
import os
import re
import subprocess
import sys

ROOT = Path(os.environ.get("HIC_ROOT", "/home/jzc/zhichengjiang/working/ai_workspace/hic")).resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hic.status import system_snapshot  # noqa: E402


DEFAULT_REMOTE = "git@github-hic-exp:jzc-2007/hic_exp.git"
STATUS_PATH = Path("shared/DAILY_STATUS.md")


def run(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=check,
    )


def ensure_git_repo(remote: str) -> None:
    if not (ROOT / ".git").exists():
        run(["git", "init"])
    run(["git", "branch", "-M", "main"])
    remotes = run(["git", "remote"], check=False).stdout.split()
    if "origin" in remotes:
        run(["git", "remote", "set-url", "origin", remote])
    else:
        run(["git", "remote", "add", "origin", remote])


def compact(value: Any, limit: int = 120) -> str:
    text = " ".join(str(value or "-").replace("|", "/").split())
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "..."


def status_entry(day: str, generated_at: str) -> str:
    snap = system_snapshot(ROOT)
    daemon_label = "alive" if snap.get("daemon_alive") else "not alive"
    db = snap.get("db") or {}
    db_label = "ok" if db.get("ok") else "not ok"
    lines = [
        f"## {day}",
        "",
        f"- generated_at_utc: {generated_at}",
        f"- daemon: {daemon_label}",
        f"- runner: {snap.get('runner_mode') or '-'}",
        f"- db: {db_label}",
        f"- overdue_agents: {', '.join(snap.get('overdue_agents') or []) or 'none'}",
        "",
        "| Agent | Activity | Last Wake | Next Wake | Current Work | Summary |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for agent in snap.get("agents") or []:
        lines.append(
            "| {agent} | {activity} | {last_wake} | {next_wake} | {work} | {summary} |".format(
                agent=compact(agent.get("display_name") or agent.get("slug")),
                activity=compact(agent.get("activity_label")),
                last_wake=compact(agent.get("last_wake_at")),
                next_wake=compact(agent.get("next_wake_at")),
                work=compact(agent.get("current_task")),
                summary=compact(agent.get("status_summary"), 180),
            )
        )
    lines.append("")
    return "\n".join(lines)


def update_daily_status(*, force: bool = False) -> bool:
    now = datetime.now(timezone.utc)
    day = now.strftime("%Y-%m-%d")
    generated_at = now.isoformat(timespec="seconds")
    path = ROOT / STATUS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    header = "# HIC Daily Status\n\n"
    note = "Generated by `scripts/daily_status_update.py`. One deterministic snapshot is recorded per UTC day.\n\n"
    entry = status_entry(day, generated_at)
    pattern = re.compile(rf"^## {re.escape(day)}\n.*?(?=^## \d{{4}}-\d\d-\d\d\n|\Z)", re.M | re.S)
    if pattern.search(existing):
        if not force:
            print(f"daily status for {day} already exists; no update")
            return False
        updated = pattern.sub(entry + "\n", existing)
    else:
        body = existing
        if body.startswith(header):
            body = body[len(header) :]
        if body.startswith(note):
            body = body[len(note) :]
        updated = header + note + entry + "\n" + (body if body.startswith("\n") or not body else "\n" + body)
    if updated != existing:
        path.write_text(updated, encoding="utf-8")
        print(f"updated {STATUS_PATH} for {day}")
        return True
    print(f"{STATUS_PATH} unchanged")
    return False


def commit_and_push(remote: str, *, push: bool, status_updated: bool) -> None:
    if not status_updated:
        return
    ensure_git_repo(remote)
    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    run(["git", "add", "-A"])
    diff = run(["git", "diff", "--cached", "--quiet"], check=False)
    if diff.returncode == 0:
        print("nothing staged for daily commit")
        return
    run(["git", "commit", "-m", f"daily hic status {day}"])
    print(f"committed daily hic status {day}")
    if push:
        output = run(["git", "push", "-u", "origin", "main"]).stdout
        print(output.rstrip())


def main() -> int:
    parser = argparse.ArgumentParser(description="Record and optionally push a daily deterministic HIC status snapshot.")
    parser.add_argument("--remote", default=os.environ.get("HIC_GIT_REMOTE", DEFAULT_REMOTE))
    parser.add_argument("--commit", action="store_true", help="commit the daily snapshot if it changed")
    parser.add_argument("--push", action="store_true", help="commit and push the daily snapshot if it changed")
    parser.add_argument("--force", action="store_true", help="replace today's snapshot if it already exists")
    args = parser.parse_args()
    updated = update_daily_status(force=args.force)
    if args.commit or args.push:
        commit_and_push(args.remote, push=args.push, status_updated=updated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
